Add main menu
freecodecamp-spb/web-dev-cources pull request #110
Opened 2017-01-08 11:26 UTC by alexbaumgertner

![screen shot 2017-01-08 at 14 24 32](https://cloud.githubusercontent.com/assets/223620/21749350/36286dd6-d5ae-11e6-8df2-83054d18ec23.png)

2017-01-08 11:33 UTC, ierhyna requested changes

2017-01-08 11:33 UTC, ierhyna commented on src/App.css
> +  width: 100%;
тут лучше писать `flex: 1 1 100%`, и не писать ширину 100%. Потому что если будет больше чем 2 элемента, все развалится в сафари

2017-01-10 17:48 UTC, alexbaumgertner commented on src/App.css
> +  width: 100%;
@ierhyna поправил, спасибо!

2017-01-10 18:03 UTC, ierhyna approved these changes

2017-01-10 18:04 UTC, merged